{
  imports = [
    ./audio.nix
    ./bluetooth.nix
    ./boot.nix
    ./dbus.nix
    ./fonts.nix
    ./i18n.nix
    ./keyd.nix
    ./network.nix
    ./nix.nix
    ./nvidia.nix
    ./opengl.nix
    ./power.nix
    ./packages.nix
    ./printing.nix
    ./security.nix
    ./shell.nix
    ./udisks2.nix
    ./unfree.nix
    ./virtualisation.nix
    ./xdg-portal.nix
  ];
}
